service: crowdfunding-api

provider:
  name: aws
  runtime: nodejs16.x
  region: us-east-1
  environment:
    PROJECTS_TABLE: Projects
    JWT_SECRET: ${env:JWT_SECRET}

functions:
  app:
    handler: server.handler
    events:
      - http:
          path: /projects/{proxy+}
          method: any
          cors: true
